name: gym-duckietown
channels:
    - defaults
dependencies:
    - python=3.6
    - pyzmq
    - numpy
    - pyyaml=3.12
    - pip:
        - gym
        - pyglet
        - scikit-image
        - dataclasses
        - pygeometry
