version: 2
jobs:
  test-3.10: &template
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:  apt-get install xvfb freeglut3-dev
#      - run: pip3 install --user -r requirements.pin.txt
#      - run: pip3 install --user -r requirements.txt
      - run: pip3 install --user . # do not install editable
      - run: pip3 install --user flake8
      - run: python3 -m flake8 . --count --show-source --statistics --select=E901,E999,F821,F822,F823
      - run:
          command: |
            ls
            xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" ./run_tests.py
  test-3.8:
    <<: *template
    docker:
      - image: ubuntu:20.04
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-3.8:
          context: pip-staging
